server:
  # Optional. Use port 8000 if not specified.
  port: 8000
  # Optional. Use port true if not specified. Perform a startup request to each provider of speech-to-text,
  # text-to-speech, and llm upon server initialization.
  # Shutdown the server if there are any errors, such as invalid API key or connection error.
  # Log a warning if there are any issues, such as quota exhaustion or incorrect transcriptions, indicating a potential problem
  # These requests consume a minimal amount of quota or even no quota.
  eager-check-providers: true
  # Optional. Enable basic auth only when there is at least one pair of username and password.
  basic-auth:
    - username1: password1
    - username2: password2

speech-to-text:
  open-ai-whisper:
    api-key: sk-abc123abc123abc123abc123abc123abc123

text-to-speech:
  elevenlabs:
    api-key: abc123abc123abc1
    voice-id: P9sd8KYc82I23b9dUJm # Optional. Use this voice whenever available, or randomly select a voice from the voice list
    expressive: 50 # Optional. Range: 0~100. Use 50(50%) if not specified. Increasing `expressive` can make speech more expressive. It can also lead to instabilities.
    clarity: 50 #Optional. Range: 0~100. Use 50(50%) if not specified. Increasing `clarity` can make speech more clarity. It can also lead to more background artifacts.

llm:
  open-ai-chat-gpt:
    api-key: sk-abc123abc123abc123abc123abc123abc123 # typically, you would use the same API key as speech-to-text.open-ai-whisper
    model: gpt-3.5-turbo # Optional. Use gpt-3.5-turbo if not specified
    max-generation-token: 2000 # Optional. Use 2000 if not specified

# options for ChatGPT model:
# gpt-4-32k-0613
# gpt-4-32k-0314
# gpt-4-32k
# gpt-4-0613
# gpt-4-0314
# gpt-4
# gpt-3.5-turbo-0613
# gpt-3.5-turbo-0301
# gpt-3.5-turbo-16k
# gpt-3.5-turbo-16k-0613
# gpt-3.5-turbo
# gpt-3.5-turbo-instruct
