package api

import "github.com/proxoar/talk/pkg/client"

const (
	EvenMessageThinking     = "message/thinking"
	EvenMessageTextTyping   = "message/text/typing"
	EvenMessageTextEOF      = "message/text/EOF"
	EvenMessageAudio        = "message/audio"
	EvenMessageError        = "message/error"
	EventSystemAbility      = "system/ability"
	EventSystemNotification = "system/notification"
)

type ContentCmd string

/*
* thinking -> typing -> EOF
*	|		    |
*	|		    v
*	|-------> error
*   |
*   v
*   EOF
 */

type MessageMeta struct {
	ConvId    string      `json:"convId"`    // unique ID for every conversation
	MessageID string      `json:"messageID"` // a ID generated by server
	Role      client.Role `json:"role"`
}

type Text struct {
	MessageMeta
	Text string `json:"text"`
}

type Audio struct {
	MessageMeta
	Audio []byte `json:"audio"`
}

type Error struct {
	MessageMeta
	EMessage string `json:"text"`
}
