server:
  # Optional. Use port 8000 if not specified.
  port: 8000
  # Optional. Enable auth only if there is at least one password
  passwords:
    - "pass1"
    - "my-pass"
    - "password"

llm:
  open-ai-chat-gpt:
    api-key: sk-abc123abc123abc123abc123abc123abc123

speech-to-text:
  open-ai-whisper:
    # typically, you would use the same API key as llm.open-ai-chat-gpt.api-key
    api-key: sk-abc123abc123abc123abc123abc123abc123

text-to-speech:
  elevenlabs:
    api-key: abc123abc123abc1
  google-text-to-speech:
    service-account-json: |
      {
        "type": "service_account",
        "project_id": "extreme-voice-356782",
        "private_key_id": "8adsf7634895yh87d09gud09g7d86g9fg8df09g",
        "private_key": "-----BEGIN PRIVATE KEY-----\xxxxxxxxxxxxxxxx=\n-----END PRIVATE KEY-----\n",
        "client_email": "354-4fgfdg-65546@extreme-voice-34534.iam.gserviceaccount.com",
        "client_id": "64565467568678798789789768",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/speech-and-text-3463456357dfgm.gserviceaccount.com",
        "universe_domain": "googleapis.com"
      }
