server:
  # Optional. Use port 8000 if not specified.
  port: 8000
  # Optional. Send a request to each server to check their accessibility status on startup. This should utilize minimal or no quota.
  check-health-on-startup: true
  # Optional. Enable auth only if there is at least one password
  passwords:
    - "pass1"
    - "my-pass"
    - "password"

speech-to-text:
  whisper: open-ai-01

llm:
  chat-gpt: open-ai-01

text-to-speech:
  elevenlabs: elevenlabs-01

# provide your confidential information below.
creds:
  open-ai-01: "sk-2dwY1IAeEysbnDNuAKJDXofX1IAeEysbnDNuAKJDXofXF5"
  elevenlabs-01: "711sfpb9kk15sds8m4czuk5rozvp43a4"